# Monitor configuration
monitor = DP-2, preferred, 0x0, 1.5 
monitor = HDMI-A-1, preferred, 2560x0, 1.5

misc {
    disable_hyprland_logo = true
    disable_splash_rendering = true
    force_default_wallpaper = 0
}

xwayland {
  force_zero_scaling=true
  }

# NVIDIA fixes
env = LIBVA_DRIVER_NAME,nvidia
env = __GLX_VENDOR_LIBRARY_NAME,nvidia
env = GBM_BACKEND,nvidia-drm
env = WLR_NO_HARDWARE_CURSORS,1
env = QT_AUTO_SCREEN_SCALE_FACTOR,1
env = GDK_SCALE,1
env = GDK_BACKEND,wayland,x11,*
env = QT_QPA_PLATFORM,wayland;xcb
env = SDL_VIDEODRIVER,wayland
env = ELECTRON_OZONE_PLATFORM_HINT,wayland
env = WARP_SCALE_FACTOR,1.5

# Polkit agent
exec-once = /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1
exec-once = elephant
exec-once = walker --gapplication-service
# exec-once = nwg-dock-hyprland -x -f -p bottom -i 32 -a start -lp start -c walker
exec-once = ~/.config/hypr/wallpaper.sh

# Firefox config
env = MOZ_ENABLE_WAYLAND,1

# Chromium
bind = SUPER, C, exec, chromium --ozone-platform=wayland --enable-features=UseOzonePlatform

# Keybinds
bind = SUPER, RETURN, exec, kitty
bind = SUPER, B, exec, firefox
bind = SUPER, D, exec, walker
bind = SUPER, E, exit
bind = SUPER, F, togglefloating
bind = SUPER, M, fullscreen
bind = SUPER, N, exec, nautilus
bind = SUPER, Q, killactive
bind = SUPER, P, exec, 1password
bind = SUPER, S, exec, spotify-launcher

# Mouse commands
bindm = SUPER, mouse:272, movewindow
bindm = SUPER, mouse:273, resizewindow

# Volume control
bind = , XF86AudioRaiseVolume, exec, pamixer -i 5
bind = , XF86AudioLowerVolume, exec, pamixer -d 5
bind = , XF86AudioMute, exec, pamixer -t

# Start waybar
exec-once = waybar

# Start hyprlock
exec-once = hypridle
bind = SUPER, L, exec, hyprlock

# Workspaces
## bind workspace to monitor
workspace = 1, monitor:DP-2, default:true
workspace = 3, monitor:DP-2, default:true
workspace = 5, monitor:DP-2, default:true
workspace = 7, monitor:DP-2, default:true
workspace = 9, monitor:DP-2, default:true
workspace = 2, monitor:HDMI-A-1, default:true
workspace = 4, monitor:HDMI-A-1, default:true
workspace = 6, monitor:HDMI-A-1, default:true
workspace = 8, monitor:HDMI-A-1, default:true

bind = SUPER, 1, workspace, 1
bind = SUPER, 2, workspace, 2
bind = SUPER, 3, workspace, 3
bind = SUPER, 4, workspace, 4
bind = SUPER, 5, workspace, 5
bind = SUPER, 6, workspace, 6
bind = SUPER, 7, workspace, 7
bind = SUPER, 8, workspace, 8
bind = SUPER, 9, workspace, 9

# Screenshot Keybinds
# Full screen screenshot → saved to ~/Pictures/Screenshots
bind = , Print, exec, grimblast save output ~/Pictures/Screenshots/$(date +%Y-%m-%d_%H-%M-%S).png

# Selection screenshot → saved to ~/Pictures/Screenshots
bind = SHIFT, Print, exec, grimblast save area ~/Pictures/Screenshots/$(date +%Y-%m-%d_%H-%M-%S).png

# Full screen → clipboard only (no file saved)
bind = CTRL, Print, exec, grimblast copy output

# Selection → clipboard only
bind = CTRL SHIFT, Print, exec, grimblast copy area
